config/routes.rb
Blogger::Application.routes.draw do


  root :to => 'articles#index'
  resources :tags
  resources :comments
  resources :articles

  resources :author_sessions
  resources :authors

  match 'login'  => 'author_sessions#new',     :as => :login
  match 'logout' => 'author_sessions#destroy', :as => :logout
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :image

  has_many :comments
  has_many :taggings
  has_many :tags, :through => :taggings
  has_attached_file :image  

  def tag_list
    return self.tags.join(", ")
  end

  def tag_list=(tags_string)
    self.taggings.destroy_all
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq

    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by_nome(tag_name)
      tagging = self.taggings.new
      tagging.tag_id = tag.id
    end
  end

  def increment_count_view
    if self.view_count
      self.view_count += 1
    else
      self.view_count = 1
    end
  end

  def self.top_3
    Article.order('view_count DESC limit 3')
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author_name, :body

  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :nome


  has_many :taggings
  has_many :articles, :through => :taggings

  def to_s
    nome
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  attr_accessible :article_id, :tag_id

  belongs_to :article
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :except => [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id]) 

    @comment = Comment.new
    @comment.article_id = @article.id
    @article.increment_count_view
    @article.save
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    @article.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])

    flash[:message] = "Article '#{@article.title}' Updated!"
    redirect_to article_path(@article)
  end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
    @author = Author.new
  end

  def create
    if @author = login(params[:username], params[:password])
      redirect_back_or_to(articles_path, :message => 'Logged in successfully.')
    else
      flash.now[:alert] = "Login failed."
      render :action => :new
    end
  end

  def destroy
    logout
    redirect_to(:login, :message => 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_filter :zero_authors_or_authenticated, :only => [:new, :create]
  before_filter :require_login, :except => [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, :except => [:create]

  def create
    article_id = params[:comment].delete(:article_id)

    @comment = Comment.new(params[:comment])
    @comment.article_id = article_id
    @comment.save

    redirect_to article_path(@comment.article)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, :only => [:destroy]

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def tag_links(tags)
    links = tags.collect{|tag| link_to tag.nome, tag_path(tag)}
    return links.join(", ").html_safe
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div class="comment">
  <h4>Comment by <%= comment.author_name %> Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at)%> later</h4>
  <p><%= comment.body %></p>
</div>

app/views/articles/_comment_form.html.erb
<h3>Post a Comment</h3>

<%= form_for @comment do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:multipart => true}) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <% if @article.image_file_name %>
        <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render :partial => "form" %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
    <%= link_to article.title,  article_path(article),
        :class => 'article_title', :id => "article_#{article.id}" %>
    <%= "#{article.view_count.to_s} visualizações" %>
    </li>
  <% end %>
</ul>

<% if logged_in? %>
  <%= link_to "new_post", new_article_path, :class => "new_article" %>
<% end %>

<h3>Top 3 mais vistos</h3>
<ul>
  <% Article.top_3.each do |art| %>
    <li> <%= art.title %>
    </li>
  <% end %>
</ul>  

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render :partial => "form" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>Tags: <%= tag_links(@article.tags) %></p>

<p>
  <% if @article.image_file_name %>
    <%= image_tag @article.image.url %> <br/>
  <% end %>
</p>

<p><%= @article.body %></p>
<p>
<h3>Comments (<%= @article.comments.count %>)</h3>
  <%= render :partial => "comment", :collection => @article.comments %>
  <%= render :partial => "comment_form" %>
  <%= link_to "<< Back to Articles List", articles_path %>
  <% if logged_in? %>
    <%= link_to "delete", article_path(@article), 
      :method => :delete,
      :data   => { :confirm => 'Really delete the article?' } %>
    <%= link_to "edit", edit_article_path(@article) %>
  <% end %>
</p>

app/views/author_sessions/new.html.erb
<h1>Login</h1>
  <%= form_tag(author_sessions_path, :method => :post) do %>

  <p>
    username<br />
    <%= text_field_tag "username" %>
  </p>
  <p>
    password<br />
    <%= text_field_tag "password"%>
  </p>
  <p>
    <%= submit_tag 'Submit' %>
  </p>
  <% end %>  

  <%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Crypted password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.username %></td>
    <td><%= author.email %></td>
    <td><%= author.crypted_password %></td>
    <td><%= author.salt %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @author.username %>
</p>

<p>
  <b>Email:</b>
  <%= @author.email %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash[:message] %> </p>
<%= yield %>
<h6>
  <% if logged_in? %>
    <%= "Logged in as #{current_user.username}" %>
    <%= link_to "(logout)", logout_path %>
  <% else %>
    <%= link_to "(login)", login_path %>
  <% end %>
</h6>
</body>
</html>

app/views/tags/index.html.erb
<h1>Todas as Tags</h1>

<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.nome, tag_path(tag) %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.nome %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>